config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :movies do
    resources :reviews
    member do
      post :favorite
      post :unlike
    end
  end

  namespace :account do
    resources :reviews
    resources :movies
  end
  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true
  belongs_to :user
  has_many :reviews

  scope :recent, -> { order("created_at DESC") }

  has_many :movie_favs
  has_many :members, through: :movie_favs, source: :user
end

app/models/movie_fav.rb
class MovieFav < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  validates :content, presence: true

  scope :recent, -> { order("created_at DESC") }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :movies
  has_many :reviews

  has_many :movie_favs
  has_many :fav_movies, :through => :movie_favs, :source => :movie

  def movie_favorite?(movie)
    fav_movies.include?(movie)
  end

  def favorite!(movie)
    fav_movies << movie
  end

  def unlike!(movie)
    fav_movies.delete(movie)
  end
end

app/controllers/account/movies_controller.rb
class Account::MoviesController < ApplicationController
  before_action :authenticate_user!

  def index
    @movies = current_user.fav_movies.all.paginate(:page => params[:page], :per_page => 5)
  end
end

app/controllers/account/reviews_controller.rb
class Account::ReviewsController < ApplicationController
  before_action :authenticate_user!

  def index
    @reviews = current_user.reviews.all.paginate(:page => params[:page], :per_page => 5)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  def index
    @movies = Movie.all.recent.paginate(:page => params[:page], :per_page => 5)
  end

  def show
    @movie = Movie.find(params[:id])
    @reviews = @movie.reviews.all.recent.paginate(:page => params[:page], :per_page => 5)
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.user = current_user
    current_user.favorite!(@movie)

    if @movie.save
      redirect_to movies_path
    else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to movies_path, notice: "电影更新成功"
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path, alert: "电影删除成功"
  end

  def favorite
    @movie = Movie.find(params[:id])

    if !current_user.movie_favorite?(@movie)
      current_user.favorite!(@movie)
      flash[:notice] = "收藏成功"
    else
      flash[:warning] = "您已收藏过了"
    end
    redirect_to movie_path(@movie)
  end

  def unlike
    @movie = Movie.find(params[:id])

    if current_user.movie_favorite?(@movie)
      current_user.unlike!(@movie)
      flash[:alert] = "取消收藏"
    else
      flash[:warning] = "没有收藏，不用取消"
    end
    redirect_to movie_path(@movie)
  end

  private

  def movie_params
    params.require(:movie).permit(:title,:description)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def index
    @movie = Movie.find(params[:movie_id])
    @review = Review.all.recent.paginate(:page => params[:page], :per_page => 5)
  end

  def show
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
  end

  def new
    @movie = Movie.find(params[:movie_id])
    @review = Review.new
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @review = Review.new(review_params)
    @review.movie = @movie
    @review.user = current_user

    if @review.save
      redirect_to movie_path(@movie)
    else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
    @review.movie = @movie
    @review.user = current_user

    if @review.update(review_params)
      redirect_to account_reviews_path, notice: "评论更新成功"
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to account_reviews_path, alert: "评论删除成功"
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:alert] = "good"
  end
end

app/helpers/account/movies_helper.rb
module Account::MoviesHelper
end

app/helpers/account/reviews_helper.rb
module Account::ReviewsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { notice: "success", warning: "warning", alert: "danger"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "notice", "warning", "alert"
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key,value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">x</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top:100px;">
  <p class="text-center">CopyRight @2017 Movie Review
    <br>Design by
    <a href="#">Michael</a>
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="nav navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href="/" class="navbar-brand">Movie Review</a>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li><%= link_to("注册", new_user_registration_path ) %></li>
          <li><%= link_to(content_tag(:i, '登录', class: 'fa fa-sign-in'), new_user_session_path ) %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi!, <%= current_user.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to("我收藏的电影", account_movies_path) %></li>
              <li><%= link_to("我发表的评论", account_reviews_path) %></li>
              <li class="divider"></li>
              <li><%= link_to(content_tag(:i, '退出', class: 'fa fa-sign-out'), destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails101Movie</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid" style="margin-top: 70px;">
      <%= render "common/navbar" %>
      <div class="row">
        <%= render "common/flashes" %>
      </div>
      <%= yield %>
    </div>
    <%= render "common/footer" %>
  </body>
</html>

app/views/movies/_movie.html.erb
<%= simple_form_for @movie do |f| %>

  <%= f.input :title %>
  <%= f.input :description %>

  <%= f.submit "Submit" %>
<% end %>

app/views/movies/edit.html.erb
<h1>编缉电影</h1>

<%= render "movie" %>

app/views/movies/index.html.erb
<div class="pull-right">
  <% if current_user %>
    <%= link_to("增加电影", new_movie_path(@movie), class: :"btn btn-primary btn-sm") %>
  <% end %>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>电影名</th>
      <th>上映时间</th>
      <th>创建者</th>
      <th>管理选项</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
    <tr>
      <td><%= movie.id %></td>
      <td><%= link_to(movie.title, movie_path(movie)) %></td>
      <td><%= movie.created_at %></td>
      <td><%= movie.user.email %></td>
      <td>
        <% if current_user && current_user == movie.user %>
          <%= link_to("编缉电影", edit_movie_path(movie), class: :"btn btn-success btn-xs") %>
          <%= link_to("删除电影", movie_path(movie), method: :delete, class: :"btn btn-danger btn-xs") %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="text-center col-md-12 pagination">
  <%= will_paginate @movies, renderer: BootstrapPagination::Rails %>
</div>

app/views/movies/new.html.erb
<h1>增加电影</h1>

<%= render "movie" %>

app/views/movies/show.html.erb
<div class="col-md-12">

  <span class="pull-right">
    <% if current_user && current_user.movie_favorite?(@movie) %>
        <%= link_to("取消收藏", unlike_movie_path(@movie), method: :post, class: :"btn btn-danger btn-xs")%>
        <%= link_to("发表评论", new_movie_review_path(@movie), class: :"btn btn-primary pull-right") %>
    <% else %>
        <%= link_to("收藏成功", favorite_movie_path(@movie), method: :post, class: :"btn btn-success btn-xs") %>
    <% end %>
  </span>

<h1><%= @movie.title %></h1>

<p>
  <%= simple_format(@movie.description) %>
</p>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>评论内容</th>
      <th>发表人</th>
      <th>发表时间</th>
    </tr>
  </thead>
  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.content %></td>
        <td><%= review.user.email %></td>
        <td><%= review.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

<div class="text-center col-md-12 pagination">
  <%= will_paginate @reviews, renderer: BootstrapPagination::Rails %>
</div>

app/views/reviews/_review.html.erb
<%= simple_form_for [@movie,@review] do |f| %>

  <%= f.input :content %>

  <%= f.submit "Submit" %>

<% end %>

app/views/reviews/edit.html.erb
<h2>编缉评论</h2>

<%= render "review" %>

app/views/reviews/new.html.erb
<h1>新增评论</h1>

<%= render "review" %>

app/views/welcome/index.html.erb
<h1>Hello World</h1>